#!/usr/bin/env perl -T
#
# dennis
#
# The Perl interface to editing and rebuilding DNS.
# Configuration options can be found in etc/dennis.conf
#
# (C) Copyright 1997-2025 Jauder Ho <jauderho@carumba.com>
#
#    This program is free software; you can redistribute it and/or modify it
#    under the terms of the GNU General Public License as published by the Free
#    Software Foundation; either version 2 of the License, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful, but
#    WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
#    or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#    for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc., 59
#    Temple Place, Suite 330, Boston, MA 02111-1307, USA
#

use strict;
use warnings;

$ENV{PATH} = '/bin:/usr/bin:/usr/sbin:/usr/local/bin:/var/named/bin';

my $dnshome       = '/var/named';
my $fileBuildLock = "$dnshome/locks/editDNS.lock";
my $fileHosts     = "$dnshome/etc/hosts";

if ( -f $fileBuildLock ) {
    die "ERROR: DNS is currently being edited. If you are sure that this is not the case, then remove $fileBuildLock\n";
}

# Create the lock file
open( my $lock_fh, '>', $fileBuildLock ) or die "Cannot create lock file $fileBuildLock: $!";
close($lock_fh);

# Edit the hosts file
system('vi', $fileHosts) == 0 or die "Editor 'vi' failed: $?";

system('clear');

print "Verifying host table syntax...\n";
system('dnsVerify') == 0 or warn "dnsVerify failed: $?";
print "\n";

print "Do you want to rebuild the dns tables [y/N]? ";
my $answer = <STDIN>;
chomp($answer);

if ( $answer =~ /^[Yy]/ ) {
    system('clear');
    print "Building DNS now...\n";
    system('dennisBuild') == 0     or warn "dennisBuild failed: $?";
    system('createSecondary') == 0 or warn "createSecondary failed: $?";
}

# Remove the lock file
unlink($fileBuildLock) or die "Cannot remove lock file $fileBuildLock: $!";

print "\n";
exit 0;
