name: Semgrep

on:
  #pull_request: {}
  push:
    branches:
    - main
    - master

permissions: read-all

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-22.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34 # v1
      with:
        egress-policy: block
        allowed-endpoints: 
          github.com:443
          metrics.semgrep.dev:443
          semgrep.dev:443
        
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2
    
    - uses: returntocorp/semgrep-action@080fad80c948b9876a4166d7d19cea656d6f1118 # v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
