name: Semgrep

on:
  #pull_request: {}
  push:
    branches:
    - main
    - master

permissions: read-all

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-22.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v1
      with:
        egress-policy: block
        allowed-endpoints: 
          github.com:443
          metrics.semgrep.dev:443
          semgrep.dev:443
        
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v2
    
    - uses: returntocorp/semgrep-action@d84805b41d957ec12d8310e77a07912acb88999a # v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
