name: Semgrep

on:
  #pull_request: {}
  push:
    branches:
    - main
    - master

permissions: read-all

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-22.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v1
      with:
        egress-policy: block
        allowed-endpoints: 
          github.com:443
          metrics.semgrep.dev:443
          semgrep.dev:443
        
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v2
    
    - uses: returntocorp/semgrep-action@713efdd345f3035192eaa63f56867b88e63e4e5d # v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
