name: Semgrep

on:
  #pull_request: {}
  push:
    branches:
    - main
    - master

permissions: read-all

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-22.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # v1
      with:
        egress-policy: block
        allowed-endpoints: 
          github.com:443
          metrics.semgrep.dev:443
          semgrep.dev:443
        
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v2
    
    - uses: returntocorp/semgrep-action@9d0e5a1dbfaf51e4c3a5026d12c65508fe58f191 # v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
