name: Semgrep

on:
  #pull_request: {}
  push:
    branches:
    - main
    - master

permissions: read-all

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-22.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v1
      with:
        egress-policy: block
        allowed-endpoints: 
          github.com:443
          metrics.semgrep.dev:443
          semgrep.dev:443
        
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v2
    
    - uses: returntocorp/semgrep-action@549796168c0ddcb9149b10a0e79e5f6522f50797 # v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
